# Generated by Django 3.1.5 on 2021-02-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rule',
            new_name='ချိုးဖောက်မှုပုဒ်မများ',
        ),
    ]
